version: '3.8'

x-shared-envs: &envs
  DB_HOST: mongo
  DB_PORT: 27017
  DB_DATABASE: mernproject
  DB_USERNAME: root
  DB_PASSWORD: rootpassword

services:
  nodejs:
    build:
      context: ./
      dockerfile: nodejs.dockerfile
      target: base
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./social-media
        target: /usr/src/app
    env_file:
      - ./social-media/.env
    environment:
      <<: *envs
    depends_on:
      - mongo
    ports: 
      - 4000:80
  mongo:
    restart: always
    image: mongo:4.2.0
    environment:
      <<: *envs
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mernproject
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
volumes:
  mongodb:
  mongodb_config:
