services:
  nodejs:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: nodejs.dockerfile
      target: base
    volumes:
      - type: bind
        source: ./mern_skeleton
        target: /usr/src/app
    depends_on:
      - mongo
    ports: 
      - 4000:80
  mongo:
    restart: unless-stopped
    image: mongo:4.2.0
    volumes:
      - type: volume
        target: /data/db
    expose:
      - 27017
