version: '3.8'

services:
  mongo:
    restart: always
    image: mongo:4.2.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: mernproject
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    networks:
      - node-network
  nodejs:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: nodejs.dockerfile
      target: base
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo:27017/mernproject?authSource=admin
    volumes:
      - type: bind
        source: ./mern_skeleton
        target: /usr/src/app
    depends_on:
      - mongo
    ports: 
      - 4000:80
    networks:
      - node-network
volumes:
  mongodb:
  mongodb_config:
networks:
  node-network:
    driver: bridge
